name: Build WF
on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main
    
  workflow_dispatch:

  schedule:
    - cron: '15 21 * * 1-5'

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5

      - name: Maven Build
        run: mvn install
      
      - name: Upload Build Artifacts (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war
      
      - name: Notify if Build Fails
        if: failure()
        run: echo " Build Failed! Please Check Logs!!!"

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Run tests on main branch
        if: github.ref == 'refs/heads/main'
        run: mvn test
      
      - name: Checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle

      - name: Run Tests on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "Skipping unit tests and code analysis"
  
  Security_Scan:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Run Trivy Filesystem Security_Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: json
          exit-code: 0
          vuln-type: os,library
          output: trivy-results.json
      
      - name: Upload Security Scan Artifacts from Trivy
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.json